version: "3.3"
services:
  php:
    image: yiisoftware/yii2-php:7.4-fpm
    working_dir: /app
    volumes:
      - .:/app
  db-sort:
    image: postgres:11
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}