version: "3.3"
services:
  php:
    build:
      context: docker
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PHP_ENABLE_XDEBUG=1
      - PHP_USER_ID=1000
      - PHP_IDE_CONFIG=serverName=sort
  db-sort:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}